application: previousnext/lamp

prepare: &prepare
  - composer install --prefer-dist --dev
  - bundle install --path vendor/bundle
  - npm install
  - mkdir -p app/sites/default/files/tmp
  - mkdir -p app/sites/default/private
  - bin/phing build -Dapp.password=$PASSWORD
  - bin/phing gulp:build
  - bin/phing styleguide:link

test: &test
  - bin/phing test
  - node_modules/.bin/gulp lint:js-with-fail
  - node_modules/.bin/gulp lint:sass-with-fail

test_pr:
  setup: *prepare
  steps: *test

test_head:
  setup: *prepare
  steps: *test

deploy_setup: &deploy_setup
  # Build the dependencies.
  - composer install --prefer-dist --no-progress
  - bundle install --path vendor/bundle
  - npm install --loglevel silent
  # We need an app dir or gulp will be unhappy.
  - mkdir app
  # Setup the remote repository.
  - git remote add drupal pnx-bot@git.drupal.org:project/agov.git
  - git fetch drupal
  - git config --global user.email "admin@previousnext.com.au"
  - git config --global user.name "PreviousNext"

deploy_teardown: &deploy_teardown
  # Remove the remote repository.
  - git remote remove drupal

deploy_7_1:
  setup: *deploy_setup
  steps:
    # Update local build before we do anything else.
    - git rebase drupal/7.x-1.x
    # Push changes to Drupal.org.
    - git push drupal 7.x-1.x
  teardown: *deploy_teardown

deploy_7_2:
  setup: *deploy_setup
  steps:
    # Update local build before we do anything else.
    - git rebase drupal/7.x-2.x
    # Push changes to Drupal.org.
    - git push drupal 7.x-2.x
  teardown: *deploy_teardown

deploy_7_3:
  setup: *deploy_setup
  steps:
    # Update local build before we do anything else.
    - git rebase drupal/7.x-3.x
    # Generate assets.
    - bin/phing gulp:build
    # Remove sass cache.
    - find themes/agov -type d -name .sass-cache -exec rm -rf {} +
    # Add and commit the compiled assets.
    - git add -Af themes/agov styleguide
    - git commit -m "Committing compiled assets and styleguide for Drupal.org"
    - git push drupal 7.x-3.x
  teardown: *deploy_teardown
